### ISSUE TITLE
error

### ISSUE THREAD

**Issue by iamutkarshpandey** [jameszah/ESP32-CAM-Video-Telegram#10]
hey, thanks for the code.
here i am facing some problem during compiling, everything's version is as mentioned.

Arduino: 1.8.13 (Windows 10), Board: "ESP32 Wrover Module, Huge APP (3MB No OTA/1MB SPIFFS), DIO, 40MHz, 921600, None"

exec: "cmd": executable file not found in %PATH%

Error compiling for board ESP32 Wrover Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by jameszah** [comment]
That looks like an arduino install problem.  Maybe restart arduino, reboot, or re-install the IDE.  The "path" stuff should be all automatic if the arduino is installed correctly.
