### ISSUE TITLE
One error shown when compiling 

### ISSUE THREAD

**Issue by roni9733** [jameszah/ESP32-CAM-Video-Telegram#11]
Please help:
Error shown:
/data/data/name.antonsmirnov.android.arduinodroid2/sketch/UniversalTelegramBot.h:29:25: fatal error: ArduinoJson.h: No such file or directory

**Comment by jameszah** [comment]
https://github.com/jameszah/ESP32-CAM-Video-Telegram/blob/e873c1b99c4ccb658240fab9d3b673fa2ba023c9/ESP32-CAM-Video-Telegram_8.8x.ino#L34

![image](https://user-images.githubusercontent.com/36938190/146840515-38ca2417-6565-45d7-b945-f31bf90f3b70.png)
