### ISSUE TITLE
PIR function photo problem

### ISSUE THREAD

**Issue by JackFrap** [jameszah/ESP32-CAM-Video-Telegram#48]
If I disable avi, when PIR is activated it sends a photo of some time before.
Is it possible to use PIR function sending just a live photo intsead of a video ?
Thank you 🙏

**Comment by FBMinis** [comment]
This fixed the old pic issue for me: https://github.com/jameszah/ESP32-CAM-Video-Telegram/issues/31

You can disable sending a video with the /disavi command.

**Comment by hakam007** [comment]
hello sir I am also facing the same issue have you resolved this problem..... thank you

**Comment by JackFrap** [comment]
I followed the directions of thread #31 discarding the first 4 photos, and it worked for me

**Comment by FBMinis** [comment]
You should close the issue.
